<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Denizs-MBP-2.fios-router.home" failures="1" tests="6" name="Command line test" time="35.359" errors="0" timestamp="2022-05-22T13:07:35 EDT">
  <testcase classname="scripts._03_EtsyTest" name="testEtsyLogo" time="0.673"/>
  <testcase classname="scripts._03_EtsyTest" name="testEtsySearch" time="0.75"/>
  <testcase classname="scripts._02_TechGlobalTest" name="testApplicationFormHeading" time="0.701"/>
  <testcase classname="scripts._01_AppleTest" name="X" time="0.0">
    <failure type="java.lang.AssertionError" message="Failure on purpose">
      <![CDATA[java.lang.AssertionError: Failure on purpose
at scripts._01_AppleTest.X(_01_AppleTest.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- X -->
  <testcase classname="scripts._01_AppleTest" name="testAppleTitle" time="0.929"/>
  <testcase classname="scripts._01_AppleTest" name="testAppleURL" time="0.934"/>
</testsuite> <!-- Command line test -->
